### PR TITLE
fix(model_claude): tool call with empty arguments

### LINKED ISSUE #238: Claude: Tools without arguments
When using Claude with Tools that dont have arguments, the eino tool component fails with "failed to unmarshal arguments in json" (empty string)

This happens cause the empty json string is stripped from the arguments. 
https://github.com/cloudwego/eino-ext/blame/a2545a66f5cf63a9a582182fbff72bf752ec38c9/components/model/claude/claude.go#L625

This only happens when streaming and I understand why you removing the `{}`.

I dont really know where to fix this. But probably add here:
https://github.com/cloudwego/eino/blob/e17d69d5a166100226cd1213c9069879438a55d5/components/tool/utils/invokable_func.go#L135

a check like, if arguments == "" then arguments == "{}"

### PR DESCRIPTION
**Pull request by mrh997**
#### Check the PR title.

- [ ] This PR title match the format: \<type\>(optional scope): \<description\>
- [ ] The description of this PR title is user-oriented and clear enough for others to understand.
- [ ] Attach the PR updating the user documentation if the current PR requires user awareness at the usage level. [User docs repo](https://github.com/cloudwego/cloudwego.github.io)

#### (Optional) More detailed description for this PR(en: English/zh: Chinese).

en:
zh(optional): 

#### (Optional) Which issue(s) this PR fixes:

Fixes #238 #462

### CODE REVIEW

**Review by hi-pender — APPROVED** [review]

File: components/model/claude/claude.go [hunk 1]
```diff
@@ -685,9 +691,15 @@ func convSchemaMessage(message *schema.Message) (mp anthropic.MessageParam, err
 	}
 
 	for i := range message.ToolCalls {
-		messageParams = append(messageParams, anthropic.NewToolUseBlock(message.ToolCalls[i].ID,
-			json.RawMessage(message.ToolCalls[i].Function.Arguments),
-			message.ToolCalls[i].Function.Name))
+		tc := message.ToolCalls[i]
```
Comment (meguminnnnnnnnn) [inline components/model/claude/claude.go:694]: 这个也加个主食吧

Comment (mrh997) [reply components/model/claude/claude.go:694]: done
